# Generated by Django 3.0.6 on 2020-06-17 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
